# Generated by Django 3.2.5 on 2021-07-10 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('descricao', models.CharField(blank=True, max_length=512)),
                ('categoria', models.IntegerField()),
                ('criado_data', models.DateField(auto_now_add=True)),
                ('criado_hora', models.TimeField(auto_now_add=True)),
                ('modificado_data', models.DateField(auto_now=True)),
                ('modificado_hora', models.TimeField(auto_now=True)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
