# Generated by Django 3.2.5 on 2021-07-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('descricao', models.CharField(blank=True, max_length=512)),
                ('categoria', models.CharField(max_length=64)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('data', models.DateTimeField()),
                ('horário', models.DateTimeField()),
            ],
        ),
    ]
