# Generated by Django 3.2.5 on 2021-07-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='horário',
            new_name='horario',
        ),
    ]
