# Generated by Django 3.2.5 on 2021-07-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210713_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitude',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
