# Generated by Django 3.2.5 on 2021-07-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='link',
            field=models.CharField(default='discord.gg/teste', max_length=256),
        ),
    ]
